### ISSUE TITLE
missing :sha in coordinate.

### ISSUE THREAD

**Issue by rkaransing** [nextjournal/clerk-demo#7]
Team, I just cloned `https://github.com/nextjournal/clerk-demo/` in my InteliJ and  I am getting the below error when it is trying to resolve dependencies with deps.edn 

`Errors during project resolution
  The following errors were found during project resolve:
   /Users/karansingrajput/clerk/clerk-demo/deps.edn:
  Library io.github.nextjournal/clerk has missing :sha in coordinate.`
  
  Here is my deps.edn
  
 {:nextjournal/clerk
  ;; we might use a version of Clerk which is ahead of main for demo purposes
  {:override-deps {io.github.nextjournal/clerk {:git/sha "37d3686f8f475a7aef1d34b147f043b31dfd50a7"}}
   :extra-paths ["datasets"]
   :exec-fn nextjournal.clerk/build-static-app!
   ;; notebooks to be built, accepts globs patterns
   :exec-args {:bundle? false
               :paths ["index.md"
                       "notebooks/introduction.clj"
                       "notebooks/data_science.clj"
                       "notebooks/semantic.clj"
                       "notebooks/sicmutils.clj"
                       "notebooks/rule_30.clj"]}}}
  
  Can anyone please help me, Thanks in Advance 🙏

**Comment by mk** [comment]
Hi @rkaransing,

The issue you're seeing should be solved by updating your clojure cli tools. We're specifying `:git/sha` instead of the older `:sha` which requires https://clojure.org/releases/tools#v1.10.3.933.

If you tell me what platform you're on I can point you to more specific upgrade instructions.

Please let me know if this solves your issue and reopen in case it does not. Thank you!

**Comment by rkaransing** [comment]
Thanks @mk for the response, currently I am on 

```
(clojure-version)
=> "1.8.0" 
```

And I added `:sha` along with other attributes and it worked temporarily for me will update here once I upgrade to ``1.10.3.933``
